### ISSUE TITLE
RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 0

### ISSUE THREAD

**Issue by alexshaodong** [zhongshuxin11/STConvLSTM#3]
Traceback (most recent call last):
  File "run.py", line 299, in <module>
    train_wrapper(model)
  File "run.py", line 185, in train_wrapper
    tr_loss = trainer.train(model, ims, real_input_flag, args, epoch)
  File "/home/n503/桌面/shaodongwei/STConvLSTM-master/trainer_loader.py", line 12, in train
    cost = model.train(ims, real_input_flag, itr)
  File "/home/n503/桌面/shaodongwei/STConvLSTM-master/models/model_factory.py", line 48, in train
    next_frames = self.network(frames_tensor, mask_tensor, itr)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/n503/桌面/shaodongwei/STConvLSTM-master/models/stconvlstm.py", line 58, in forward
    net = mask_true[:, t - self.configs.input_length] * frames[:, t] + \
RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 0

**Comment by Zhou-Yuqi** [comment]
I have the same question...
